name: "Pipeline DEV"

on:
  push:
    branches: [ dev ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: dev
      aws-region: "us-east-2"
      aws-state-s3-bucket: "posmack-pipeline-github-bucket"
      aws-lock-table: "posmack-pipeline-github-lock-table"
      aws-assume-role-arn: "arn:aws:iam::381491937821:role/posmack-gitactions-pipeline-role"